across:
  development:
    active: true

acrossHibernate:
  hibernate-properties:
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.show_sql: false
  hibernate:
    ddl-auto: update

server:
  error:
    includeStacktrace: ALWAYS
  port: 36449

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/bookPublisher-db"
    username: sa
